name: TestActions

on:
  push:
    branches:
      - main
  schedule:
    - cron: 00 02 * * *
jobs:
  build-and-run:
    runs-on: ubuntu-20.04
    name: Crawl
    steps:
      - name: Setup Chrome
        run: |
          sudo apt install gdebi-core wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          google-chrome --version
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Run
        run: |
          python3 main.py
